ORI_IMG_HEIGHT = 180
ORI_IMG_WIDTH = 180
IMG_HEIGHT = 128
IMG_WIDTH = 128
NUM_CHANNEL = 3
NUM_CLASS = 5
IMAGE_DIR_BASE = '../animal_images'
LOG_DIR = 'logs'
BATCH_SIZE = 50
# TRAIN_STEPS = 400
NUM_EPOCH = 50
BATCH_PER_EPOCH = 12

NUM_VAL_BATCH = 4
NUM_TEST_BATCH = 4